In [1]:
import pandas as pd

In [2]:
data_factorySolarGen = pd.read_csv('Generacion_fotovoltaica.csv')
data_gridInput = pd.read_csv('Consumo.csv')
data_Weather = pd.read_csv('Meteorologia.csv')
data_CarbonIntensity23 = pd.read_csv('ES_2023_hourly.csv')
data_CarbonIntensity24 = pd.read_csv('ES_2024_hourly.csv')
data_CarbonIntensity = pd.concat([data_CarbonIntensity23, data_CarbonIntensity24], ignore_index=True)
data_factorySolarUse = pd.read_csv('Consumo_fotovoltaica.csv')

In [3]:
def renameAndIndex(df,datetime):
    df=df.rename(columns={datetime:'TIMESTAMP'})
    df['TIMESTAMP']=pd.to_datetime(df['TIMESTAMP'])
    df.set_index('TIMESTAMP', inplace=True)
    return df

In [4]:
data_factorySolarGen = renameAndIndex(data_factorySolarGen,'FECHA')
data_gridInput = renameAndIndex(data_gridInput,'FECHA')
data_Weather = renameAndIndex(data_Weather,'FORECAST_TIMESTAMP')
data_CarbonIntensity = renameAndIndex(data_CarbonIntensity,'Datetime (UTC)')
data_factorySolarUse = renameAndIndex(data_factorySolarUse,'FECHA')

In [5]:
allDatasets = {
    "factorySolarGen": data_factorySolarGen,
    "gridInput": data_gridInput,
    "weather": data_Weather,
    "carbonIntensity": data_CarbonIntensity,
    "factorySolarUse": data_factorySolarUse
}

minMaxDates = {}
for name, dataset in allDatasets.items():
    min_date = dataset.index.min()
    max_date = dataset.index.max()
    dataLen = len(dataset)
    minMaxDates[name] = {"min": min_date, "max": max_date, "rows":dataLen}

timeframes = pd.DataFrame(minMaxDates)

timeframes

,factorySolarGen,gridInput,weather,carbonIntensity,factorySolarUse
min,2023-07-24 11:00:00,2023-07-24 11:00:00,2023-07-24 11:00:00+00:00,2023-01-01 00:00:00,2024-09-01 00:00:00+02:00
max,2024-08-31 23:00:00,2024-08-31 23:00:00,2024-10-31 23:00:00+00:00,2024-12-31 23:00:00,2024-10-17 23:00:00+02:00
rows,9708,9708,100557,17544,1128

In [6]:
coords = data_Weather[['LATITUDE', 'LONGITUDE']].drop_duplicates().values.tolist()
coords

# Since the weather data is collected from 9 distinct points, according to the EDA, we can average these 9 points to get an accurate reading, as we don't know exact factory location

data_Weather.groupby('TIMESTAMP').mean()

,LATITUDE,LONGITUDE,10uheightAboveGround_10,10vheightAboveGround_10,2rheightAboveGround_2,2shheightAboveGround_2,2theightAboveGround_2,SUNSDsurface_0,aptmpheightAboveGround_2,dlwrfsurface_0,...,spsurface_0,tccatmosphere_0,theightAboveGround_80,tmaxheightAboveGround_2,tminheightAboveGround_2,tozneatmosphereSingleLayer_0,tpsurface_0,tsurface_0,uheightAboveGround_80,vheightAboveGround_80
TIMESTAMP,,,,,,,,,,,,,,,,,,,,,
2023-07-24 11:00:00+00:00,40.25,-3.75,5.176383,2.306685,17.577778,0.004644,301.823414,18000.0,300.332920,320.641024,...,94006.964236,2.700000,299.178662,301.843240,293.290378,324.906396,0.000000,315.466679,5.985768,2.433457
2023-07-24 12:00:00+00:00,40.25,-3.75,5.670802,2.579575,16.988889,0.004856,303.187798,21600.0,301.359812,324.429913,...,93949.704861,3.800000,300.411111,303.219008,293.290378,325.770036,0.000000,317.400000,6.652786,2.790844
2023-07-24 13:00:00+00:00,40.25,-3.75,6.260587,2.442148,17.077778,0.005225,304.332392,3600.0,302.303198,352.366667,...,93885.935417,38.833333,301.517803,304.326211,303.222222,326.296606,0.000000,318.032850,7.447305,2.665181
2023-07-24 14:00:00+00:00,40.25,-3.75,7.004427,2.025345,17.266667,0.005513,305.103729,7200.0,302.988475,356.926508,...,93829.203819,23.177778,302.366265,305.123018,303.222222,327.157633,0.000000,317.471498,8.407716,2.233926
2023-07-24 15:00:00+00:00,40.25,-3.75,7.471493,2.054768,17.411111,0.005703,305.553950,10800.0,303.401274,360.544444,...,93770.919444,58.177778,303.032275,305.617803,303.222222,330.289266,0.000000,315.935266,8.912477,2.333355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-31 19:00:00+00:00,40.25,-3.75,1.712167,-0.120578,73.222222,0.008330,288.451378,0.0,288.458230,332.734110,...,94665.164583,42.044444,288.438051,289.342572,288.244711,295.169328,0.013889,287.852675,2.547099,0.112466
2024-10-31 20:00:00+00:00,40.25,-3.75,1.172493,0.060525,75.133333,0.008365,288.053681,0.0,288.046803,326.544554,...,94687.728819,54.911111,288.217674,289.467016,287.635614,295.584785,0.013889,287.270662,1.844787,0.230565
2024-10-31 21:00:00+00:00,40.25,-3.75,0.838918,0.100157,74.722222,0.008353,288.091836,0.0,288.100517,328.326836,...,94711.029167,71.344444,288.150030,289.579238,287.398305,295.179774,0.013889,287.248275,1.417429,0.248963
2024-10-31 22:00:00+00:00,40.25,-3.75,0.230694,0.130402,74.233333,0.008353,288.164748,0.0,288.187877,332.423588,...,94727.309028,88.144444,288.075634,289.626970,287.278305,294.312722,0.020833,287.526053,0.637383,0.258828
2024-10-31 23:00:00+00:00,40.25,-3.75,0.101007,0.667309,73.988889,0.008331,288.179941,0.0,288.184033,337.176019,...,94733.415278,98.455556,287.908186,289.635497,287.192750,292.976552,0.027778,287.496525,0.324520,0.899162

In [8]:
from geopy.distance import geodesic  # accurate distance calculation

repsolPintoCoords = [40.265468,3.738145] # Solar installation location from GMaps

grid_coords = coords
target_coord = repsolPintoCoords

distances = [geodesic(coord, target_coord).kilometers for coord in grid_coords]

inv_distances = [1/d if d != 0 else 1e9 for d in distances]  # Avoid division by zero
total = sum(inv_distances)
weights = [w/total for w in inv_distances]

point_names = [f"point{i+1}" for i in range(len(grid_coords))]
weight_mapping = dict(zip(point_names, weights))

weight_mapping

{'point1': 0.10720746604685572,
 'point2': 0.1107769808999071,
 'point3': 0.11459233323129474,
 'point4': 0.10751129449897934,
 'point5': 0.1110984057425242,
 'point6': 0.11493338303484028,
 'point7': 0.10762598661154862,
 'point8': 0.11121101834000828,
 'point9': 0.11504313159404178}

In [ ]:
point_labels = [f"point{i+1}" for i in range(len(coords))]

coord_to_label = {tuple(coord): label for coord, label in zip(coords, point_labels)}

data_Weather['point'] = data_Weather[['LATITUDE', 'LONGITUDE']].apply(
    lambda row: coord_to_label.get((row['LATITUDE'], row['LONGITUDE']), None),
    axis=1
)

data_Weather['weight'] = data_Weather['station'].map(weight_mapping)

columns_to_weight = ['temperature', 'wind_speed', 'humidity']  # replace with your actual columns

for col in columns_to_weight:
    data_Weather[col] = data_Weather[col] * data_Weather['weight']

data_Weather.drop('weight')

In [9]:
combined_df = pd.concat([
    data_factorySolarGen.add_prefix("SG_"),
    data_gridInput.add_prefix("GI_"),
    data_Weather.add_prefix("W_")
], axis=1, join='inner')

InvalidIndexError: Reindexing only valid with uniquely valued Index objects